[package]
name = "slint-hmi-app"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"

[build-dependencies]
slint-build = "1.3"
